version: '3'

services:
    nukerduit-db:
        image: postgres:16
        container_name: nukerduit-db
        environment:
            POSTGRES_USER: "nukerduit"
            POSTGRES_PASSWORD: "C0b4l4g1"
            POSTGRES_DB: "nukerduit"
        ports:
            - "5433:5432"

    nukerduit-app:
        build:
            context: ./nukerduit-app
            dockerfile: Dockerfile
        container_name: nukerduit-app
        working_dir: /app/nukerduit-app
        ports:
            - "5173:5173"
    nukerduit-service:
        build:
            context: ./nukerduit-service
            dockerfile: Dockerfile
        container_name: nukerduit-service
        working_dir: /app/nukerduit-service
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=nukerduit-db
            - DB_PORT=5432
            - DB_USER=nukerduit
            - DB_PASSWORD=C0b4l4g1
            - DB_NAME=nukerduit
        depends_on:
            - nukerduit-db

networks:
    default:
        external: true
        name: gateway
